spring.application.name=AgroSan
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=AgroSanDB;encrypt=true;TrustServerCertificate=True;
spring.datasource.username=sa
spring.datasource.password=sql
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Logging configuration
logging.level.pe.edu.uni.app=DEBUG
logging.level.pe.edu.uni.app.rest=DEBUG
logging.level.pe.edu.uni.app.config=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.filter=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %level - %msg%n